#!/usr/bin/env bash
# WHAT: Generates one NodeNetworkConfigurationPolicy per WORKER node (bond0 + three VLAN
#       sub-interfaces on top, for InternalAPI/Storage/Tenant) and applies them all.
#       FIXES A REAL BUG: the original repo had exactly one static NNCP file hardcoded to
#       worker-0, and scripts/02-deploy-networking.sh only ever applied that single file - on a
#       3-worker cluster, worker-1 and worker-2 (including whichever one is the Compute data-plane
#       node) never got the isolated-network VLANs at all, so RHOSO pods scheduled there would
#       fail to reach InternalAPI/Storage/Tenant.
# WHY GENERATED RATHER THAN STATIC FILES: worker count is a variable (terraform's worker_count),
#       not a fixed number, so a template + generator scales to any node count without hand-editing
#       N near-identical YAML files.
# NODE SOURCE: prefers terraform/generated/nodes/*.json (written by every
#       modules/baremetal_node.local_file.node_manifest, regardless of platform_mode) so the
#       bond member interface names/mode here always match what terraform/templates/agent-config.yaml.tmpl
#       booted the node with. Falls back to $WORKER_NODES (space-separated hostnames) if you did
#       not use this repo's terraform/ at all.
# VERIFY: oc get nncp
#         oc get nnce   # NodeNetworkConfigurationEnactment - per-node status, must be Available
# ROLLBACK: oc delete nncp -l app=rhoso-poc-worker-vlans
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
NODES_DIR="${REPO_ROOT}/terraform/generated/nodes"
OUT_DIR="${SCRIPT_DIR}/generated"

BOND_IFACE="${BOND_IFACE:-bond0}"
BOND_MODE="${BOND_MODE:-802.3ad}"
BOND_MIIMON="${BOND_MIIMON:-140}"
BOND_MEMBER1="${BOND_MEMBER1:-eno1}"
BOND_MEMBER2="${BOND_MEMBER2:-eno2}"

mkdir -p "${OUT_DIR}"
rm -f "${OUT_DIR}"/*.yaml

emit_nncp() {
  local node="$1" internalapi_ip="$2" storage_ip="$3" tenant_ip="$4"
  cat > "${OUT_DIR}/${node}-osp-vlans.yaml" <<YAML
# Generated by 03-generate-nncp.sh - do not hand-edit, re-run the generator instead.
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ${node}-osp-vlans
  labels:
    app: rhoso-poc-worker-vlans
spec:
  nodeSelector:
    kubernetes.io/hostname: ${node}
  desiredState:
    interfaces:
      # Re-declares the same bond0 booted at install time (terraform/templates/agent-config.yaml.tmpl)
      # so the NMState operator now owns/manages it going forward - this block is intentionally
      # idempotent with what agent-config.yaml set, not a second/competing bond.
      - name: ${BOND_IFACE}
        type: bond
        state: up
        link-aggregation:
          mode: ${BOND_MODE}
          options:
            miimon: '${BOND_MIIMON}'
          port:
            - ${BOND_MEMBER1}
            - ${BOND_MEMBER2}
      - name: ${BOND_IFACE}.20   # InternalAPI
        type: vlan
        state: up
        vlan:
          base-iface: ${BOND_IFACE}
          id: 20
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: ${internalapi_ip}
              prefix-length: 24
      - name: ${BOND_IFACE}.21   # Storage
        type: vlan
        state: up
        vlan:
          base-iface: ${BOND_IFACE}
          id: 21
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: ${storage_ip}
              prefix-length: 24
      - name: ${BOND_IFACE}.22   # Tenant (Neutron/OVN geneve)
        type: vlan
        state: up
        vlan:
          base-iface: ${BOND_IFACE}
          id: 22
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: ${tenant_ip}
              prefix-length: 24
YAML
}

# CHANGE_ME - the third octet pattern below (172.1{7,8,9}.0.<n>) just needs to land inside each
# VLAN's NetConfig-disjoint range (02-netconfig.yaml documents .100-250 for EDPM/OCP nodes,
# .30-70 reserved for NAD whereabouts pods) - <n> below starts at 100 and increments per worker.
i=100
if [ -d "${NODES_DIR}" ] && ls "${NODES_DIR}"/*.json >/dev/null 2>&1; then
  echo "== Reading node list from ${NODES_DIR} (terraform output) =="
  for f in "${NODES_DIR}"/*.json; do
    role=$(python3 -c "import json;print(json.load(open('${f}'))['role'])")
    [ "${role}" = "worker" ] || continue
    node=$(python3 -c "import json;print(json.load(open('${f}'))['name'])")
    emit_nncp "${node}" "172.17.0.${i}" "172.18.0.${i}" "172.19.0.${i}"
    i=$((i + 1))
  done
elif [ -n "${WORKER_NODES:-}" ]; then
  echo "== Reading node list from \$WORKER_NODES (no terraform/generated/nodes found) =="
  for node in ${WORKER_NODES}; do
    emit_nncp "${node}" "172.17.0.${i}" "172.18.0.${i}" "172.19.0.${i}"
    i=$((i + 1))
  done
else
  echo "ERROR: no node source found. Either run 'terraform apply' first (terraform/generated/nodes/*.json)" >&2
  echo "  or set WORKER_NODES='worker-0 worker-1 compute-0' and re-run this script." >&2
  exit 1
fi

echo "== Applying $(ls "${OUT_DIR}"/*.yaml | wc -l) generated NNCP(s) =="
oc apply -f "${OUT_DIR}/"
